org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# https://fabricmc.net/develop
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT
fabric_api_version=0.133.14+1.21.9

mod_version=1.1.11-alpha.1
maven_group=com.arematics
archives_base_name=AdvancedChatBox

advancedchat_version=1.21.9-1.5.16-alpha.1
# https://jitpack.io/#sakura-ryoko/malilib
malilib_version=1.21.9-pre4-0.26.0-pre4
# https://repo.maven.apache.org/maven2/org/mariuszgromada/math/MathParser.org-mXparser
mxparser_version=4.4.2

modrinth_slug=advancedchatbox-next
modrinth_id=mcyXhvtp

# default_release_type can be stable, beta, or alpha
default_release_type=stable
project_name=AdvancedChatBox
project_url=https://modrinth.com/mod/advancedchatbox-next
project_logo=https://raw.githubusercontent.com/DarkKronicle/AdvancedChatBox/main/src/main/resources/assets/advancedchatbox/icon.png
project_color=0x4480ad
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
discord_webhook_changelog_line_limit=10
